include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    always_declare_return_types: true
    avoid_print: true
    sort_child_properties_last: true
    require_trailing_commas: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "build/**"
